### PR TITLE
Fix directory creation on collect command

### LINKED ISSUE #90: The `collect` command should create all necessary sub-directories in the output folder
When running the `collect` command, a target output folder needs to be specified, however, it doesn't create the `commercial` sub-folder automatically and errors out if it doesn't exist. It seems the [logic exists](https://github.com/elastic/esdiag/blob/b6681dab0e496a736c6702e86e2092e9c7746cc3/src/exporter/directory.rs#L35-L39), but didn't work out in the below case.

Sample run:
```
% mkdir ~/Downloads/api-diagnostics-20250205-114500 
% esdiag collect test_cluster ~/Downloads/api-diagnostics-20250205-114500
[2025-02-05T12:45:21.614Z INFO  esdiag] Collecting diagnostic from KnownHost ApiKey: Elasticsearch https://test-val.es.us-east-1.aws.found.io/ <redacted>
[2025-02-05T12:45:21.614Z INFO  esdiag] Saving diagnostic to /Users/<redacted>/Downloads/api-diagnostics-20250205-114500
[2025-02-05T12:45:22.208Z INFO  esdiag::data::collector::elasticsearch] Saved diagnostic_manifest.json
[2025-02-05T12:45:35.427Z INFO  esdiag::data::collector::elasticsearch] Saved alias.json
[2025-02-05T12:45:35.552Z INFO  esdiag::data::collector::elasticsearch] Saved version.json
[2025-02-05T12:45:35.739Z INFO  esdiag::data::collector::elasticsearch] Saved cluster_settings_defaults.json
[2025-02-05T12:45:36.017Z ERROR esdiag::data::collector::elasticsearch] Failed to save commercial/data_stream.json: No such file or directory (os error 2)
[2025-02-05T12:45:37.730Z ERROR esdiag::data::collector::elasticsearch] Failed to save commercial/ilm_explain.json: No such file or directory (os error 2)
[2025-02-05T12:45:40.479Z INFO  esdiag::data::collector::elasticsearch] Saved settings.json
[2025-02-05T12:45:44.873Z INFO  esdiag::data::collector::elasticsearch] Saved indices_stats.json
[2025-02-05T12:45:45.116Z INFO  esdiag::data::collector::elasticsearch] Saved nodes.json
[2025-02-05T12:45:45.864Z INFO  esdiag::data::collector::elasticsearch] Saved nodes_stats.json
[2025-02-05T12:45:46.038Z ERROR esdiag::data::collector::elasticsearch] Failed to save commercial/searchable_snapshots_cache_stats.json: No such file or directory (os error 2)
[2025-02-05T12:45:55.367Z ERROR esdiag::data::collector::elasticsearch] Failed to save commercial/searchable_snapshots_stats.json: No such file or directory (os error 2)
[2025-02-05T12:45:55.548Z INFO  esdiag::data::collector::elasticsearch] Saved tasks.json
[2025-02-05T12:45:55.548Z INFO  esdiag::data::collector] Collected 9 of 13 files into /Users/<redacted>/Downloads/api-diagnostics-20250205-114500
[2025-02-05T12:45:55.549Z INFO  esdiag] collect complete in 33.936 seconds
```

After creating the `commercial` sub-folder and re-running the `collect` command, it worked like a charm.

### PR DESCRIPTION
**Pull request by VimCommando**
Using the `collect` subcommand now creates an `api-diagnostic-{datetime}` subdirectory.

Also improved error message when providing a non-existent directory.

Fixes #90

### CODE REVIEW

File: src/exporter/directory.rs [hunk 1]
```diff
@@ -32,18 +32,15 @@ impl TryFrom<PathBuf> for DirectoryExporter {
...
-            log::debug!("Creating directory: {}", &subpath.display());
-            std::fs::create_dir_all(subpath)?;
-        }
-        match path.is_dir() {
-            true => Ok(Self { path }),
-            false => Err(eyre!(
-                "Directory input must be a directory: {}",
-                path.display()
-            )),
+            return Err(eyre!("Directory output not fount: {}", path.display()));
```
Comment (consulthys) [inline src/exporter/directory.rs]: Small typo `fount` => `found`
